---
- name: Auditbeat for RHEL
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family is match("RedHat")
  tags:
    - create
    - remove

- name: Auditbeat for Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family is match("Windows")
  tags:
    - create
    - remove